---
services:
  weasyprint-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}  # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to container logs
    volumes:
      - weasyprint_service_logs:/opt/weasyprint/logs  # Use named volume for logs
    ports:
      - 9080:9080  # Adjust port as needed for your application
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9080/health]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
volumes:
  weasyprint_service_logs:
    name: ${COMPOSE_PROJECT_NAME:-weasyprint}_logs
    driver: local
