---
name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read  # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@738d95884b633748912ad70a5eb33a45f5bfb8e0  # v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

    # Optional: Uncomment and customize as needed
    # trigger_phrase: "@claude"  # Custom trigger phrase instead of @claude
    # assignee_trigger: true  # Trigger when assigned to issues/PRs
    # claude_args: "--model claude-3-5-sonnet-20241022"  # Custom Claude arguments
    # project_context: "This is a Python web service"  # Additional project context
